# Generated by Django 5.0 on 2023-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sidebar_menus_remove_sidebar_social_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='profile',
            field=models.FileField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='logo',
            field=models.FileField(upload_to='logos'),
        ),
    ]
