# Generated by Django 5.0 on 2023-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sidebar_profile_alter_sociallinks_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='\n        <h3>Hi, I\'m <span class="blueColor">Elisc!</span></h3>\n        <h3>\n        <span class="cd-headline rotate-1"> \n        <span class="blc">Creative</span>\n        <span class="cd-words-wrapper">\n        <b class="is-visible">Designer</b>\n        <b>Coder</b>\n        <b>Player</b>\n        </span>\n        </span>\n        </h3>\n        <h3>Based in Florida</h3>\n    ')),
                ('subtitle', models.TextField(default='\n        <p>I\'m a Florida based web designer &amp; front‑end developer with <span class="blueColor">10+ years</span> of experience</p>\n    ')),
                ('image', models.ImageField(upload_to='images')),
                ('btn1_text', models.CharField(default='Got a Project', max_length=500)),
                ('btn1_link', models.TextField(default='project.html')),
                ('btn2_text', models.CharField(default="Let's talk", max_length=1000)),
                ('btn2_link', models.TextField(default='contact.html')),
                ('contact_info', models.ManyToManyField(to='app.homecontactinfo')),
            ],
        ),
    ]
