# Generated by Django 5.0 on 2023-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_homecontactinfo_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('num', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=10000)),
                ('text', models.TextField()),
                ('skill', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='\n        <span class="mini">- Nice to meet you!</span>\n        <h3 class="name">Robert Elisc</h3>\n        <span class="job">\n        <span class="cd-headline rotate-1"> \n        <span class="blc">Web designer &amp;</span>\n        <span class="cd-words-wrapper">\n        <b class="is-visible">Developer</b>\n        <b>Coder</b>\n        <b>Player</b>\n        </span>\n        </span>\n        </span>\n    ')),
                ('text', models.TextField(default='\n        <p>Hello there! My name is <span class="yellowColor">Robert Elisc</span>. I am a web designer &amp; developer, and I\'m very passionate and dedicated to my work.</p>\n        <p>With 20 years experience as a professional a graphic designer, I have acquired the skills and knowledge necessary to make your project a success. I enjoy every step of the design process, from discussion and collaboration.</p>\n    ')),
                ('contact_info', models.ManyToManyField(to='app.homecontactinfo')),
                ('banner', models.ManyToManyField(to='app.aboutbanner')),
                ('skill', models.ManyToManyField(to='app.skills')),
            ],
        ),
    ]
