# Generated by Django 5.0 on 2023-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_skills_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='subtitle',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
