# Generated by Django 5.0 on 2023-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_text_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('play_btn', models.FileField(upload_to='images')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
            ],
        ),
    ]
