# Generated by Django 5.0 on 2023-12-13 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('short_text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='projects')),
                ('video_url', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
