# Generated by Django 5.0 on 2023-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('service', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
