# Generated by Django 5.0 on 2023-12-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data',
            new_name='date',
        ),
    ]
