# Generated by Django 5.0 on 2023-12-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sidebar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo'),
        ),
    ]
