# Generated by Django 5.0 on 2023-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ManyToManyField(related_name='Contact_info', to='app.contactinfo'),
        ),
    ]
