# Generated by Django 5.0 on 2023-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_contact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.TextField(default='https://www.google.com/maps?q=Bangladesh+Agricultural+Research+Institute/@23.9916906,90.4033221,15z/data=!3m1!4b1?entry=ttu=&output=embed'),
        ),
    ]
