# Generated by Django 5.0 on 2023-12-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='unique_id',
            new_name='visitor_id',
        ),
    ]
