# Generated by Django 5.0 on 2023-12-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_unique_id_visitor_visitor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
