# Generated by Django 5.0 on 2023-12-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_visitor_visited_url_visitedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedurl',
            name='total_visit',
            field=models.IntegerField(default=1),
        ),
    ]
