# Generated by Django 5.0 on 2023-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_about_page_title_blog_page_title_home_page_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='page_title',
            field=models.CharField(default='Tanjim Abubokor', max_length=100000),
        ),
    ]
