# Generated by Django 5.0 on 2023-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_contact_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
